apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccountName: foo # use foo service account
  containers:
    - name: main
      image: nightfury1204/alpine-curl
      command: ['sleep', '9999999']
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2
