apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2 # name of pod
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: dhyana1984/kubia
      name: kubia # name of container
      ports:
        - containerPort: 8080
          protocol: TCP
