apiVersion: v1
kind: Service # create a service object
metadata:
  name: kubia-session-affinity
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80 # service forward the link to container port
      targetPort: 8080
  selector: # service indludes the pods which have the labels
    app: kubia
