apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: dhyana1984/kubia
          readinessProbe: # There will be a probe in each pod. if there is no /var/ready folder, the po will not be ready
            exec:
              command:
                - ls
                - /var/ready
          ports:
            - containerPort: 8080
