apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort # Nodeport type service
  ports:
    - port: 80 # The port of service cluster IP
      targetPort: 8080 # Port port of pod
      nodePort: 30123 # visit this service by 30123 port of node cluster
  selector:
    app: kubia
