apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  containers:
    - image: luksa/fortune:env
      env: # Define env variable
        - name: INTERVAL # The name of env variable
          valueFrom: # Set the source of env variable
            configMapKeyRef: # The value of env variable is from config map
              name: fortune-config # The name of config map
              key: sleep-interval # The key in config map
      name: html-generator
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}
